SELECT DISTINCT 
        B.NR_ATENDIMENTO, 
        A.DT_PRESCRICAO,
        A.NR_PRESCRICAO NR_PRESCRICAO_P,
        B.DS_CONVENIO || ' / ' || B.DS_CATEGORIA DS_CONVENIO,
        B.DS_ANOS_MESES_DIAS DS_IDADE,
        DECODE (A.IE_RECEM_NATO, 'S', 'R.N. ', '') || B.NM_PACIENTE NM_PACIENTE,
        DECODE(B.IE_CLINICA, 3, '#'||B.DS_CLINICA||'#N#P', 90, '#'||B.DS_CLINICA||'#N#P', B.DS_CLINICA) DS_CLINICA,
        B.DT_NASCIMENTO,
        B.DT_ENTRADA,
        B.NR_PRONTUARIO, 
        A.DT_LIBERACAO_MEDICO, 
        A.DT_LIBERACAO,
        A.IE_MOTIVO_PRESCRICAO,
        B.NM_MEDICO,
        OBTER_VALOR_DOMINIO (136, A.IE_MOTIVO_PRESCRICAO) DS_MOTIVO,
        A.QT_PESO,
        B.DS_SETOR_ATENDIMENTO SETOR,
        OBTER_USUARIO_PRESCRITOR (A.NR_PRESCRICAO) NM_PRESCRITOR,
        DECODE (A.IE_ORIGEM_INF,'1', '#' || A.NM_USUARIO_ORIGINAL || '#N#P',
        A.NM_USUARIO_ORIGINAL) NM_USUARIO,
        OBTER_UNIDADE_ATENDIMENTO (A.NR_ATENDIMENTO,'A','UPA') CD_UNIDADE,
        DECODE(B.CD_CONVENIO,28,'PARTICULAR',NULL) NM_CONVENIO,
        B.DS_NIVEL_URGENCIA || DECODE(OBTER_PRIORIDADE_ATEND(A.NR_ATENDIMENTO), 4, '   -   (GESTANTE)', NULL) DS_NIVEL_URGENCIA

FROM    PRESCR_MEDICA A,
        ATENDIMENTO_PACIENTE_V B

WHERE   A.NR_ATENDIMENTO = B.NR_ATENDIMENTO
AND     A.NR_ATENDIMENTO IS NOT NULL
AND     B.IE_CLINICA in (3,79)
AND     (A.DT_LIBERACAO_MEDICO IS NOT NULL OR A.DT_LIBERACAO IS NOT NULL)
AND     A.CD_SETOR_ATENDIMENTO = 37
AND     A.DT_PRESCRICAO > SYSDATE - 1
AND     A.DT_SUSPENSAO IS NULL
AND     A.IE_FUNCAO_PRESCRITOR IN (1,3)
AND     1 = (SELECT 1 FROM PRESCR_MEDICA X WHERE
            (((SELECT COUNT(1) FROM PRESCR_SOLUCAO Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO)>0) OR
            ((SELECT COUNT(1) FROM PRESCR_MATERIAL Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO)>0) OR
            ((SELECT COUNT(1) FROM PRESCR_RECOMENDACAO Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO)>0) OR
            ((SELECT COUNT(1) FROM PRESCR_PROCEDIMENTO Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO 
            AND OBTER_TIPO_PROCEDIMENTO(Z.CD_PROCEDIMENTO,Z.IE_ORIGEM_PROCED,'C') NOT IN (1,97))>0))
            AND X.NR_PRESCRICAO = A.NR_PRESCRICAO)
AND     NOT EXISTS (SELECT 1 FROM SEP_LOG_CONTROLE X WHERE X.NR_SEQUENCIA = A.NR_PRESCRICAO AND X.IE_ORIGEM = 'CATE2870') 
AND     A.CD_PERFIL_ATIVO <> 2247



-----------------------------------------------------------------------------------------------------------------------------------------------
SELECT DISTINCT 
        B.NR_ATENDIMENTO, 
        A.DT_PRESCRICAO,
        A.NR_PRESCRICAO NR_PRESCRICAO_P,
        B.DS_CONVENIO || ' / ' || B.DS_CATEGORIA DS_CONVENIO,
        B.DS_ANOS_MESES_DIAS DS_IDADE,
        DECODE (A.IE_RECEM_NATO, 'S', 'R.N. ', '') || B.NM_PACIENTE NM_PACIENTE,
        DECODE(B.IE_CLINICA, 3, '#'||B.DS_CLINICA||'#N#P', 90, '#'||B.DS_CLINICA||'#N#P', B.DS_CLINICA) DS_CLINICA,
        B.DT_NASCIMENTO,
        B.DT_ENTRADA,
        B.NR_PRONTUARIO, 
        A.DT_LIBERACAO_MEDICO, 
        A.DT_LIBERACAO,
        A.IE_MOTIVO_PRESCRICAO,
        B.NM_MEDICO,
        OBTER_VALOR_DOMINIO (136, A.IE_MOTIVO_PRESCRICAO) DS_MOTIVO,
        A.QT_PESO,
        B.DS_SETOR_ATENDIMENTO SETOR,
        OBTER_USUARIO_PRESCRITOR (A.NR_PRESCRICAO) NM_PRESCRITOR,
        DECODE (A.IE_ORIGEM_INF,'1', '#' || A.NM_USUARIO_ORIGINAL || '#N#P',
        A.NM_USUARIO_ORIGINAL) NM_USUARIO,
        OBTER_UNIDADE_ATENDIMENTO (A.NR_ATENDIMENTO,'A','UPA') CD_UNIDADE,
        DECODE(B.CD_CONVENIO,28,'PARTICULAR',NULL) NM_CONVENIO,
        B.DS_NIVEL_URGENCIA || DECODE(OBTER_PRIORIDADE_ATEND(A.NR_ATENDIMENTO), 4, '   -   (GESTANTE)', NULL) DS_NIVEL_URGENCIA

FROM    PRESCR_MEDICA A,
        ATENDIMENTO_PACIENTE_V B

WHERE   A.NR_ATENDIMENTO = B.NR_ATENDIMENTO
AND     A.NR_ATENDIMENTO IS NOT NULL
AND     (A.DT_LIBERACAO_MEDICO IS NOT NULL OR A.DT_LIBERACAO IS NOT NULL)
AND     B.IE_CLINICA NOT IN (3,79) 
AND     A.CD_SETOR_ATENDIMENTO = 37
AND     A.DT_PRESCRICAO > SYSDATE - 1
AND     A.DT_SUSPENSAO IS NULL
AND     A.IE_FUNCAO_PRESCRITOR IN (1,3)
AND     1 = (SELECT 1 FROM PRESCR_MEDICA X WHERE
            (((SELECT COUNT(1) FROM PRESCR_SOLUCAO Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO)>0) OR
            ((SELECT COUNT(1) FROM PRESCR_MATERIAL Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO)>0) OR
            ((SELECT COUNT(1) FROM PRESCR_RECOMENDACAO Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO)>0) OR
            ((SELECT COUNT(1) FROM PRESCR_PROCEDIMENTO Z WHERE Z.NR_PRESCRICAO = A.NR_PRESCRICAO 
            AND OBTER_TIPO_PROCEDIMENTO(Z.CD_PROCEDIMENTO,Z.IE_ORIGEM_PROCED,'C') NOT IN (1,97))>0))
            AND X.NR_PRESCRICAO = A.NR_PRESCRICAO)
AND     NOT EXISTS (SELECT DISTINCT 1 FROM SEP_LOG_CONTROLE X WHERE X.NR_SEQUENCIA = A.NR_PRESCRICAO AND X.IE_ORIGEM = 'CATE1627') 
AND     A.CD_PERFIL_ATIVO <> 2247

